version: '2.1'
services:
  beat:
    build: 6.0/.
    depends_on:
      - proxy_dep
    # environment:
    #   - KIBANA_HOST=kibana
    #   - KIBANA_PORT=5601
    # working_dir: /go/src/github.com/elastic/beats/filebeat
    # volumes:
    #   - ${PWD}/..:/go/src/github.com/elastic/beats/
    #   # We launch docker containers to test docker autodiscover:
    #   - /var/run/docker.sock:/var/run/docker.sock
    command: make

  # This is a proxy used to block beats until all services are healthy.
  # See: https://github.com/docker/compose/issues/4369
  proxy_dep:
    image: busybox
    depends_on:
      elasticsearch: { condition: service_healthy }
      kibana:        { condition: service_healthy }
      redis:         { condition: service_healthy }

  elasticsearch:
      service: elasticsearch

  kibana:
      service: kibana
