# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/alexcesaro/statsd"
  version = "2.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.5"

[[constraint]]
  name = "github.com/blevesearch/bleve"
  version = "0.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/bmizerany/assert"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.0"

[[constraint]]
  name = "github.com/docker/engine-api"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/elastic/beats"
  version = "6.2.4"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ghetzel/cli"
  version = "1.16.0"

[[constraint]]
  name = "github.com/ghetzel/diecast"
  version = "1.8.16"

[[constraint]]
  name = "github.com/ghetzel/go-stockutil"
  version = "1.5.36"

[[constraint]]
  name = "github.com/ghetzel/pivot"
  version = "2.3.7"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/gocarina/gocsv"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/husobee/vestigo"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/iharsuvorau/json2csv2json"

[[constraint]]
  name = "github.com/jbenet/go-base58"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/jdxcode/netrc"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/configor"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/jscherff/json2csv"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "2.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"

[[constraint]]
  name = "github.com/optiopay/kafka"
  version = "2.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  name = "github.com/qinhao/json2csv"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/sniperkit/jargon"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"

[[constraint]]
  name = "github.com/yukithm/json2csv"
  version = "0.1.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.71"

[prune]
  go-tests = true
  unused-packages = true
